### ISSUE TITLE
Warning: JAVA_HOME environment variable is not set. Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -Dsun.zip.disableMemoryMapping=true -Dmaven.multiModuleProjectDirectory system property is not set.

### ISSUE THREAD

**Issue by abhishekshastri** [pavankjadda/BookStore#36]
Started by user [admin](https://jenkins-cicd.apps.ocp4.taashee.com/user/admin-admin-edit-view)
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] node
Running on [Jenkins](https://jenkins-cicd.apps.ocp4.taashee.com/computer/(built-in)/) in /var/lib/jenkins/jobs/Bookstore/workspace
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Tool Install)
[Pipeline] tool
[Pipeline] envVarsForTool
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Build App)
[Pipeline] tool
[Pipeline] envVarsForTool
[Pipeline] withEnv
[Pipeline] {
[Pipeline] git
The recommended git tool is: NONE
No credentials specified
 > /usr/bin/git rev-parse --resolve-git-dir /var/lib/jenkins/jobs/Bookstore/workspace/.git # timeout=10
Fetching changes from the remote Git repository
 > /usr/bin/git config remote.origin.url https://github.com/abhishekshastri/BookStore.git # timeout=10
Fetching upstream changes from https://github.com/abhishekshastri/BookStore.git
 > /usr/bin/git --version # timeout=10
 > git --version # 'git version 2.27.0'
 > /usr/bin/git fetch --tags --force --progress -- https://github.com/abhishekshastri/BookStore.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > /usr/bin/git rev-parse refs/remotes/origin/master^{commit} # timeout=10
Checking out Revision 595bc87482b5c09b5615cd5019ac2fb431804502 (refs/remotes/origin/master)
 > /usr/bin/git config core.sparsecheckout # timeout=10
 > /usr/bin/git checkout -f 595bc87482b5c09b5615cd5019ac2fb431804502 # timeout=10
 > /usr/bin/git branch -a -v --no-abbrev # timeout=10
 > /usr/bin/git branch -D master # timeout=10
 > /usr/bin/git checkout -b master 595bc87482b5c09b5615cd5019ac2fb431804502 # timeout=10
Commit message: "Update Jenkinsfile"
 > /usr/bin/git rev-list --no-walk 595bc87482b5c09b5615cd5019ac2fb431804502 # timeout=10
[Pipeline] script
[Pipeline] {
[Pipeline] readMavenPom
[Pipeline] }
[Pipeline] // script
[Pipeline] sh
+ mvn clean install -DskipTests=true
Warning: JAVA_HOME environment variable is not set.
Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -Dsun.zip.disableMemoryMapping=true
-Dmaven.multiModuleProjectDirectory system property is not set.
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Test)
Stage "Test" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Code Analysis)
Stage "Code Analysis" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Create Image Builder)
Stage "Create Image Builder" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build Image)
Stage "Build Image" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Create DEV)
Stage "Create DEV" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Deploy DEV)
Stage "Deploy DEV" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Promote to STAGE?)
Stage "Promote to STAGE?" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Deploy STAGE)
Stage "Deploy STAGE" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE

**Comment by pavankjadda** [comment]
This issue related to JAVA_HOME not being set in your machine. Set it based on OS (Windows/Mac)
